import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./component/layout/header/header";
import Footer from "./component/layout/footer";
import { TooltipProvider } from "@/components/ui/tooltip"; // Ensure the path is correct
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
/* 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 */
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // 400 is gentle, 600 is for emphasis
  variable: "--font-sans",
  display: "swap", // Prevents layout shift
});
const sans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});
const headingFont = Montserrat({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap", // Prevents layout shift
  weight: ["500", "700"],
});
const heading = Montserrat({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap", // Prevents layout shift
  weight: ["500", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${heading.variable}`}>
      <body className="min-h-full flex flex-col">
        {" "}
        <TooltipProvider delayDuration={0}>
          <Header />
          {children}
          <Footer />
        </TooltipProvider>
      </body>
    </html>
  );
}
