import { productType } from "./types";
export const PUBLICPATH = "http://localhost:3000";
export const searchItemsLists = [
  "cakes",
  "Sugarfree",
  "pastries",
  "doughnuts",
  "bagels",
  "buns",
  "sweet",
  "rolls",
  "biscuits",
  "loaf breads",
  "Hungry Chocolate",
  "cookies",
  "desserts",
  "cupcakes",
  "cheesecakes",
  "pies",
  "tortillas",
  "Fruit Garden",
  "naya",
];
export interface ProductListProps {
  products: productType[];
}
export const imagesCupcakes: productType[][] = [
  [
    {
      id: 9,
      name: "Hungry Chocolate",
      src: "../assets/images/cupcake/1.jpg",
      description:
        "Chocolate truffle torte is layered with rich moist chocolate sponge",
      price: 20,
      starRating: 4.5,
      category: [
        "cupcake",
        "cupcakes",
        "sweet",
        "cakes",
        "Hungry Chocolate",
        "naya",
      ],
    },
    {
      id: 10,
      name: "Rainbow Sparkles",
      src: "../assets/images/cupcake/2.jpg",
      description:
        "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
      price: 20,
      starRating: 4.5,
      category: [
        "cupcake",
        "cupcakes",
        "sweet",
        "sugarfree",
        "Rainbow Sparkles",
      ],
    },
    {
      id: 11,
      name: "Fruit Garden",
      src: "../assets/images/cupcake/3.jpg",
      description:
        "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
      price: 20,
      starRating: 4.5,
      category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Fruit Garden"],
    },
    {
      id: 12,
      name: "Very Berry",
      src: "../assets/images/cupcake/4.jpg",
      price: 20,
      starRating: 4.5,
      description:
        "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
      category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Very Berry"],
    },
  ],
  [
    {
      id: 13,
      name: "Hungry Chocolate",
      src: "../assets/images/cupcake/5.jpg",
      description:
        "Chocolate truffle torte is layered with rich moist chocolate ",
      price: 20,
      starRating: 4.5,
      category: [
        "cupcake",
        "cupcakes",
        "sweet",
        "sugarfree",
        "Hungry Chocolate",
      ],
    },
    {
      id: 14,
      name: "Rainbow Sparkles",
      src: "../assets/images/cupcake/1a.jpg",
      description:
        "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
      price: 20,
      starRating: 4.5,
      category: [
        "cupcake",
        "cupcakes",
        "sweet",
        "sugarfree",
        "Rainbow Sparkles",
      ],
    },
    {
      id: 15,
      name: "Rainbow Sparkles",
      src: "../assets/images/cupcake/6.jpg",
      description:
        "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
      price: 20,
      starRating: 4.5,
      category: [
        "cupcake",
        "cupcakes",
        "sweet",
        "sugarfree",
        "Rainbow Sparkles",
      ],
    },
    {
      id: 16,
      name: "Lemon Delight",
      src: "../assets/images/cupcake/7.jpg",
      description:
        "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
      price: 20,
      starRating: 4.5,
      category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Lemon Delight"],
    },
  ],
];
export const imagesCupcakesSingle: any[] = [
  {
    id: 9,
    name: "Hungry Chocolate",
    src: "../assets/images/cupcake/1.jpg",
    description:
      "Chocolate truffle torte is layered with rich moist chocolate sponge",
    price: 20,
    starRating: 4.5,
    category: [
      "cupcake",
      "cupcakes",
      "sweet",
      "cakes",
      "Hungry Chocolate",
      "naya",
    ],
  },
  {
    id: 10,
    name: "Rainbow Sparkles",
    src: "../assets/images/cupcake/2.jpg",
    description:
      "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
    price: 20,
    starRating: 4.5,
    category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Rainbow Sparkles"],
  },
  {
    id: 11,
    name: "Fruit Garden",
    src: "../assets/images/cupcake/3.jpg",
    description:
      "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
    price: 20,
    starRating: 4.5,
    category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Fruit Garden"],
  },
  {
    id: 12,
    name: "Very Berry",
    src: "../assets/images/cupcake/4.jpg",
    price: 20,
    starRating: 4.5,
    description:
      "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
    category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Very Berry"],
  },

  {
    id: 13,
    name: "Hungry Chocolate",
    src: "../assets/images/cupcake/5.jpg",
    description:
      "Chocolate truffle torte is layered with rich moist chocolate ",
    price: 20,
    starRating: 4.5,
    category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Hungry Chocolate"],
  },
  {
    id: 14,
    name: "Rainbow Sparkles",
    src: "../assets/images/cupcake/1a.jpg",
    description:
      "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
    price: 20,
    starRating: 4.5,
    category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Rainbow Sparkles"],
  },
  {
    id: 15,
    name: "Rainbow Sparkles",
    src: "../assets/images/cupcake/6.jpg",
    description:
      "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
    price: 20,
    starRating: 4.5,
    category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Rainbow Sparkles"],
  },
  {
    id: 16,
    name: "Lemon Delight",
    src: "../assets/images/cupcake/7.jpg",
    description:
      "Delightful blend of Strawberry Coulee, Berry Crumble, Richnes",
    price: 20,
    starRating: 4.5,
    category: ["cupcake", "cupcakes", "sweet", "sugarfree", "Lemon Delight"],
  },
];
export const imagesDoughnutSingle: any[] = [
  {
    id: 1,
    name: "Sinful Sugar",
    src: "../assets/images/doughnut/1.jpg",
    description: "Sinful Sugar glaze on Hevenly doughnut",
    price: 20,
    starRating: 5,
    category: ["doughnuts", "sweet", "Sinful Sugar"],
  },
  {
    id: 2,
    name: "Bagels and Buns",
    src: `../assets/images/doughnut/2.jpg`,
    description:
      "bagels, buns, rolls, biscuits and loaf breads), cookies, desserts (cakes, cheesecakes and pies and tortillas.",
    price: 30,
    starRating: 3.5,
    category: ["bagels", "buns", "rolls", "biscuits", "loaf breads"],
  },
  {
    id: 3,
    name: "Bagels, Buns and Rolls",
    src: "../assets/images/doughnut/3.jpg",
    description:
      "bagels, buns, rolls, biscuits and loaf breads), cookies, desserts (cakes, cheesecakes and pies and tortillas.",
    price: 20,
    starRating: 4.8,
    category: ["doughnuts", "sweet", "Sinful Sugar", "Hungry Chocolate"],
  },
  {
    id: 4,
    name: "Hungry Chocolate",
    src: "../assets/images/doughnut/4.jpg",
    price: 120,
    starRating: 5,
    description: "Sinful Sugar glaze on Hevenly doughnut",
    category: ["doughnuts", "sweet", "Sinful Sugar", "Hungry Chocolate"],
  },
  {
    id: 5,
    name: "Sinful Sugar",
    src: "../assets/images/doughnut/1.jpg",
    description: "Sinful Sugar glaze on Hevenly doughnut",
    price: 520,
    starRating: 5,
    category: ["doughnuts", "sweet", "Sinful Sugar"],
  },
  {
    id: 6,
    name: "Bagels and Buns",
    src: "../assets/images/doughnut/2.jpg",

    description:
      "bagels, buns, rolls, biscuits and loaf breads), cookies, desserts (cakes, cheesecakes and pies and tortillas.",
    price: 520,
    starRating: 4.3,
    category: ["bagels", "buns", "rolls", "biscuits", "loaf breads"],
  },
  {
    id: 7,
    name: "Bagels, Buns and Rolls",
    src: "../assets/images/doughnut/3.jpg",
    description:
      "bagels, buns, rolls, biscuits and loaf breads), cookies, desserts (cakes, cheesecakes and pies and tortillas.",
    price: 80,
    starRating: 4.0,
    category: ["doughnuts", "sweet", "Sinful Sugar", "Hungry Chocolate"],
  },
  {
    id: 8,
    name: "Hungry Chocolate",
    src: "../assets/images/doughnut/4.jpg",

    description: "Sinful Sugar glaze on Hevenly doughnut",
    price: 90,
    starRating: 4.6,
    category: ["doughnuts", "sweet", "Sinful Sugar", "Hungry Chocolate"],
  },
];

export const imagesDoughnut: productType[][] = [
  [
    {
      id: 1,
      name: "Sinful Sugar",
      src: "../assets/images/doughnut/1.jpg",
      description: "Sinful Sugar glaze on Hevenly doughnut",
      price: 20,
      starRating: 5,
      category: ["doughnuts", "sweet", "Sinful Sugar"],
    },
    {
      id: 2,
      name: "Bagels and Buns",
      src: "../assets/images/doughnut/2.jpg",
      description:
        "bagels, buns, rolls, biscuits and loaf breads), cookies, desserts (cakes, cheesecakes and pies and tortillas.",
      price: 30,
      starRating: 3.5,
      category: ["bagels", "buns", "rolls", "biscuits", "loaf breads"],
    },
    {
      id: 3,
      name: "Bagels, Buns and Rolls",
      src: "../assets/images/doughnut/3.jpg",
      description:
        "bagels, buns, rolls, biscuits and loaf breads), cookies, desserts (cakes, cheesecakes and pies and tortillas.",
      price: 20,
      starRating: 4.8,
      category: ["doughnuts", "sweet", "Sinful Sugar", "Hungry Chocolate"],
    },
    {
      id: 4,
      name: "Hungry Chocolate",
      src: "../assets/images/doughnut/4.jpg",
      price: 120,
      starRating: 5,
      description: "Sinful Sugar glaze on Hevenly doughnut",
      category: ["doughnuts", "sweet", "Sinful Sugar", "Hungry Chocolate"],
    },
  ],
  [
    {
      id: 5,
      name: "Sinful Sugar",
      src: "../assets/images/doughnut/1.jpg",
      description: "Sinful Sugar glaze on Hevenly doughnut",
      price: 520,
      starRating: 5,
      category: ["doughnuts", "sweet", "Sinful Sugar"],
    },
    {
      id: 6,
      name: "Bagels and Buns",
      src: "../assets/images/doughnut/2.jpg",

      description:
        "bagels, buns, rolls, biscuits and loaf breads), cookies, desserts (cakes, cheesecakes and pies and tortillas.",
      price: 520,
      starRating: 4.3,
      category: ["bagels", "buns", "rolls", "biscuits", "loaf breads"],
    },
    {
      id: 7,
      name: "Bagels, Buns and Rolls",
      src: "../assets/images/doughnut/3.jpg",
      description:
        "bagels, buns, rolls, biscuits and loaf breads), cookies, desserts (cakes, cheesecakes and pies and tortillas.",
      price: 80,
      starRating: 4.0,
      category: ["doughnuts", "sweet", "Sinful Sugar", "Hungry Chocolate"],
    },
    {
      id: 8,
      name: "Hungry Chocolate",
      src: "../assets/images/doughnut/4.jpg",

      description: "Sinful Sugar glaze on Hevenly doughnut",
      price: 90,
      starRating: 4.6,
      category: ["doughnuts", "sweet", "Sinful Sugar", "Hungry Chocolate"],
    },
  ],
];

export const imagesCakesSingle: any[] = [
  {
    id: 17,
    name: "Shaun The Sheep",
    src: "../assets/images/cakes/1.jpg",
    description: "Your Fav charecter on a cake",
    price: 20,
    starRating: 5,
    category: [
      "kids cakes",
      "custom cakes",
      "Birthday cake",
      "cake",
      "cakes",
      "sweet",
      "fun",
      "Shaun The Sheep",
    ],
  },
  {
    id: 18,
    name: "Barnie the bear",
    src: `../assets/images/cakes/2.jpg`,
    description:
      "Barnie the bear on your kids birthday cake, make birthdays more fun, celebrate with your fav charecter",
    price: 30,
    starRating: 3.5,
    category: [
      "kids cakes",
      "custom cakes",
      "Birthday cake",
      "cake",
      "cakes",
      "sweet",
      "fun",
      "Barnie Bear",
    ],
  },
  {
    id: 19,
    name: "Truffle chocolate cake",
    src: "../assets/images/cakes/4.avif",
    description: " Enjoy your birthday with our award wining recipie",
    price: 20,
    starRating: 4.8,
    category: [
      "Truffle chocolate cake",
      "custom cakes",
      "Birthday cakes",
      "Birthday cake",
      "cake",
      "cakes",
      "sweet",
    ],
  },
  {
    id: 20,
    name: "Doremon Cake",
    src: "../assets/images/cakes/doremon.jpg",
    price: 120,
    starRating: 5,
    description: "Sinful Sugar glaze on Hevenly doughnut",
    category: [
      "Truffle chocolate cake",
      "custom cakes",
      "Birthday cakes",
      "Birthday cake",
      "cake",
      "cakes",
      "sweet",
      "Doremon Cake",
    ],
  },
  {
    id: 21,
    name: "Melting colors",
    src: "../assets/images/cakes/ai-generated-7833232_640.webp",
    description: "A cake that will surprise and delight your guests..",
    price: 520,
    starRating: 5,
    category: [
      "girls",
      "custom cakes",
      "Birthday cake",
      "cake",
      "cakes",
      "sweet",
      "Melting colors",
    ],
  },
  {
    id: 22,
    name: "Blue Berry Cheesecake",
    src: "../assets/images/cakes/barry_cake.jpg",
    description:
      "Blue Berry Cheesecake, just melts in your mouth, made with blueberries espicially imported from Italian Alps",
    price: 520,
    starRating: 4.3,
    category: [
      "kids cakes",
      "custom cakes",
      "Birthday cake",
      "cake",
      "cakes",
      "sweet",
      "Blue Berry Cheesecake",
    ],
  },
  {
    id: 23,
    name: "Minions Themed Cake",
    src: "../assets/images/cakes/minion-theme-cake_-kids-birthday-cake_-trending-birthday-cakes-for-kids.jpeg",
    description: "Minions are here to wish you a happy birthday!",
    price: 80,
    starRating: 4.0,
    category: [
      "kids cakes",
      "custom cakes",
      "Birthday cake",
      "cake",
      "cakes",
      "sweet",
      "Minions  Cake",
      "Minions Themed Cake",
    ],
  },
  {
    id: 24,
    name: "Makeup set cake",
    src: "../assets/images/cakes/Designer-Cakes-For-Girls.jpeg",

    description: "make up set for you make up obsessed girlfriend",
    price: 90,
    starRating: 4.6,
    category: ["girls", "Birthday cake", "cake", "cakes", "Makeup set cake"],
  },
];
// /* 
// [
//   {
//     slug: "hungry-chocolate-cupcake-1",
//     name: "Hungry Chocolate",
//     description: "Chocolate truffle torte with rich moist sponge",
//     price: 20,
//     images: ["../assets/images/cupcake/1.jpg"],
//     category: ["cupcake", "sweet", "chocolate"],
//     stock: 10,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "sandhya-mandi",
//   },
//   {
//     slug: "rainbow-sparkles-cupcake",
//     name: "Rainbow Sparkles",
//     description: "Strawberry coulee with berry crumble",
//     price: 20,
//     images: ["../assets/images/cupcake/2.jpg"],
//     category: ["cupcake", "sweet", "fruit"],
//     stock: 8,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "priya-sharma",
//   },
//   {
//     slug: "fruit-garden-cupcake",
//     name: "Fruit Garden",
//     description: "Fresh fruit flavored cupcake",
//     price: 20,
//     images: ["../assets/images/cupcake/3.jpg"],
//     category: ["cupcake", "fruit", "sweet"],
//     stock: 6,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "ananya-das",
//   },
//   {
//     slug: "very-berry-cupcake",
//     name: "Very Berry",
//     description: "Berry rich cupcake",
//     price: 20,
//     images: ["../assets/images/cupcake/4.jpg"],
//     category: ["cupcake", "berry", "sweet"],
//     stock: 6,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "meenakshi-iyer",
//   },
//   {
//     slug: "sinful-sugar-doughnut",
//     name: "Sinful Sugar",
//     description: "Sugar glaze doughnut",
//     price: 20,
//     images: ["../assets/images/doughnut/1.jpg"],
//     category: ["doughnut", "sweet"],
//     stock: 12,
//     starRating: 5,
//     isVeg: true,
//     creatorSlug: "meenakshi-iyer",
//   },
//   {
//     slug: "bagels-and-buns",
//     name: "Bagels and Buns",
//     description: "Assorted bakery breads",
//     price: 30,
//     images: ["../assets/images/doughnut/2.jpg"],
//     category: ["bread", "buns"],
//     stock: 15,
//     starRating: 3.5,
//     isVeg: true,
//     creatorSlug: "sandhya-mandi",
//   },
//   {
//     slug: "truffle-chocolate-cake",
//     name: "Truffle Chocolate Cake",
//     description: "Rich chocolate celebration cake",
//     price: 500,
//     images: ["../assets/images/cakes/4.avif"],
//     category: ["cake", "chocolate", "birthday"],
//     stock: 5,
//     starRating: 4.8,
//     isVeg: true,
//     creatorSlug: "priya-sharma",
//   },
//   {
//     slug: "blueberry-cheesecake",
//     name: "Blue Berry Cheesecake",
//     description: "Creamy cheesecake with blueberries",
//     price: 520,
//     images: ["../assets/images/cakes/barry_cake.jpg"],
//     category: ["cake", "cheesecake", "fruit"],
//     stock: 4,
//     starRating: 4.3,
//     isVeg: true,
//     creatorSlug: "ananya-das",
//   },
//   {
//     slug: "minions-themed-cake",
//     name: "Minions Themed Cake",
//     description: "Fun kids birthday cake",
//     price: 800,
//     images: [
//       "../assets/images/cakes/minion-theme-cake_-kids-birthday-cake_-trending-birthday-cakes-for-kids.jpeg",
//     ],
//     category: ["cake", "kids", "birthday"],
//     stock: 3,
//     starRating: 4.0,
//     isVeg: true,
//     creatorSlug: "meenakshi-iyer",
//   },
 
//   {
//     slug: "hungry-chocolate-1",
//     name: "Hungry Chocolate",
//     description:
//       "Chocolate truffle torte is layered with rich moist chocolate sponge",
//     price: 20,
//     images: ["../assets/images/cupcake/1.jpg"],
//     category: ["cupcake", "sweet", "cakes", "naya"],
//     stock: 10,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "sandhya-mandi",
//   },
//   {
//     slug: "rainbow-sparkles-1",
//     name: "Rainbow Sparkles",
//     description: "Delightful blend of Strawberry Coulee, Berry Crumble",
//     price: 20,
//     images: ["../assets/images/cupcake/2.jpg"],
//     category: ["cupcake", "sweet", "sugarfree"],
//     stock: 8,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "priya-sharma",
//   },
//   {
//     slug: "fruit-garden-1",
//     name: "Fruit Garden",
//     description: "Delightful berry fruit cupcake",
//     price: 20,
//     images: ["../assets/images/cupcake/3.jpg"],
//     category: ["cupcake", "sweet", "sugarfree"],
//     stock: 8,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "meenakshi-iyer",
//   },
//   {
//     slug: "very-berry-1",
//     name: "Very Berry",
//     description: "Berry rich cupcake",
//     price: 20,
//     images: ["../assets/images/cupcake/4.jpg"],
//     category: ["cupcake", "sweet"],
//     stock: 8,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "ananya-das",
//   },

//   {
//     slug: "hungry-chocolate-2",
//     name: "Hungry Chocolate",
//     description: "Chocolate truffle variation",
//     price: 20,
//     images: ["../assets/images/cupcake/5.jpg"],
//     category: ["cupcake", "sweet"],
//     stock: 10,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "sandhya-mandi",
//   },
//   {
//     slug: "rainbow-sparkles-2",
//     name: "Rainbow Sparkles",
//     description: "Colorful berry cupcake",
//     price: 20,
//     images: ["../assets/images/cupcake/1a.jpg"],
//     category: ["cupcake", "sweet"],
//     stock: 10,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "priya-sharma",
//   },
//   {
//     slug: "rainbow-sparkles-3",
//     name: "Rainbow Sparkles",
//     description: "Rainbow cupcake",
//     price: 20,
//     images: ["../assets/images/cupcake/6.jpg"],
//     category: ["cupcake", "sweet"],
//     stock: 10,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "meenakshi-iyer",
//   },
//   {
//     slug: "lemon-delight",
//     name: "Lemon Delight",
//     description: "Zesty lemon cupcake",
//     price: 20,
//     images: ["../assets/images/cupcake/7.jpg"],
//     category: ["cupcake", "sweet", "lemon"],
//     stock: 10,
//     starRating: 4.5,
//     isVeg: true,
//     creatorSlug: "ananya-das",
//   },

//   {
//     slug: "sinful-sugar-1",
//     name: "Sinful Sugar",
//     description: "Sugar glaze doughnut",
//     price: 20,
//     images: ["../assets/images/doughnut/1.jpg"],
//     category: ["doughnut", "sweet"],
//     stock: 15,
//     starRating: 5,
//     isVeg: true,
//     creatorSlug: "meenakshi-iyer",
//   },
//   {
//     slug: "bagels-and-buns-1",
//     name: "Bagels and Buns",
//     description: "Assorted breads and buns",
//     price: 30,
//     images: ["../assets/images/doughnut/2.jpg"],
//     category: ["bread", "buns"],
//     stock: 20,
//     starRating: 3.5,
//     isVeg: true,
//     creatorSlug: "sandhya-mandi",
//   },
//   {
//     slug: "bagels-buns-rolls",
//     name: "Bagels, Buns and Rolls",
//     description: "Bakery assortment",
//     price: 20,
//     images: ["../assets/images/doughnut/3.jpg"],
//     category: ["bread", "rolls"],
//     stock: 12,
//     starRating: 4.8,
//     isVeg: true,
//     creatorSlug: "priya-sharma",
//   },
//   {
//     slug: "hungry-chocolate-doughnut",
//     name: "Hungry Chocolate",
//     description: "Chocolate doughnut",
//     price: 120,
//     images: ["../assets/images/doughnut/4.jpg"],
//     category: ["doughnut", "chocolate"],
//     stock: 10,
//     starRating: 5,
//     isVeg: true,
//     creatorSlug: "ananya-das",
//   },

//   {
//     slug: "shaun-the-sheep-cake",
//     name: "Shaun The Sheep",
//     description: "Fun kids themed cake",
//     price: 500,
//     images: ["../assets/images/cakes/1.jpg"],
//     category: ["cake", "kids", "birthday"],
//     stock: 3,
//     starRating: 5,
//     isVeg: true,
//     creatorSlug: "priya-sharma",
//   },
//   {
//     slug: "barnie-bear-cake",
//     name: "Barnie the Bear",
//     description: "Kids birthday cake",
//     price: 600,
//     images: ["../assets/images/cakes/2.jpg"],
//     category: ["cake", "kids"],
//     stock: 3,
//     starRating: 3.5,
//     isVeg: true,
//     creatorSlug: "meenakshi-iyer",
//   },
//   {
//     slug: "truffle-chocolate-cake",
//     name: "Truffle Chocolate Cake",
//     description: "Rich chocolate cake",
//     price: 700,
//     images: ["../assets/images/cakes/4.avif"],
//     category: ["cake", "chocolate"],
//     stock: 5,
//     starRating: 4.8,
//     isVeg: true,
//     creatorSlug: "sandhya-mandi",
//   },
//   {
//     name: "Hungry Chocolate Cupcake",
//     slug: "hungry-chocolate-cupcake",
//     description: "Chocolate truffle torte layered with rich moist sponge.",
//     price: "20.00",
//     category: ["cupcake", "sweet", "chocolate"],
//     images: [
//       "../assets/images/cupcake/1.jpg",
//       "../assets/images/cupcake/5.jpg",
//     ],
//     stock: 50,
//     starRating: 4.5,
//     isFeatured: true,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Rainbow Sparkles Cupcake",
//     slug: "rainbow-sparkles-cupcake",
//     description: "Strawberry coulee with berry crumble.",
//     price: "20.00",
//     category: ["cupcake", "sweet", "fruit"],
//     images: [
//       "../assets/images/cupcake/2.jpg",
//       "../assets/images/cupcake/1a.jpg",
//       "../assets/images/cupcake/6.jpg",
//     ],
//     stock: 50,
//     starRating: 4.5,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Fruit Garden Cupcake",
//     slug: "fruit-garden-cupcake",
//     description: "Fresh fruit infused cupcake.",
//     price: "20.00",
//     category: ["cupcake", "fruit", "sweet"],
//     images: ["../assets/images/cupcake/3.jpg"],
//     stock: 40,
//     starRating: 4.5,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Very Berry Cupcake",
//     slug: "very-berry-cupcake",
//     description: "Berry rich cupcake delight.",
//     price: "20.00",
//     category: ["cupcake", "berry", "sweet"],
//     images: ["../assets/images/cupcake/4.jpg"],
//     stock: 40,
//     starRating: 4.5,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Lemon Delight Cupcake",
//     slug: "lemon-delight-cupcake",
//     description: "Refreshing lemon flavored cupcake.",
//     price: "20.00",
//     category: ["cupcake", "citrus", "sweet"],
//     images: ["../assets/images/cupcake/7.jpg"],
//     stock: 40,
//     starRating: 4.5,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Sinful Sugar Doughnut",
//     slug: "sinful-sugar-doughnut",
//     description: "Sugar glazed heavenly doughnut.",
//     price: "20.00",
//     category: ["doughnut", "sweet"],
//     images: ["../assets/images/doughnut/1.jpg"],
//     stock: 60,
//     starRating: 5,
//     isFeatured: true,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Chocolate Doughnut",
//     slug: "chocolate-doughnut",
//     description: "Rich chocolate doughnut.",
//     price: "90.00",
//     category: ["doughnut", "chocolate", "sweet"],
//     images: ["../assets/images/doughnut/4.jpg"],
//     stock: 50,
//     starRating: 4.6,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Bakery Assorted Buns",
//     slug: "bakery-assorted-buns",
//     description: "Bagels, buns, rolls and breads.",
//     price: "30.00",
//     category: ["bakery", "bread"],
//     images: ["../assets/images/doughnut/2.jpg"],
//     stock: 30,
//     starRating: 3.5,
//     creatorSlug: "sweet-cravings",
//   },
//   {
    name: "Shaun The Sheep Cake",
    slug: "shaun-the-sheep-cake",
    description: "Fun themed cake for kids.",
    price: "20.00",
    category: ["cake", "kids", "custom"],
    images: ["../assets/images/cakes/1.jpg"],
    stock: 10,
    starRating: 5,
    isFeatured: true,
    creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Barney Bear Cake",
//     slug: "barney-bear-cake",
//     description: "Cute birthday cake for kids.",
//     price: "30.00",
//     category: ["cake", "kids"],
//     images: ["../assets/images/cakes/2.jpg"],
//     stock: 10,
//     starRating: 3.5,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Truffle Chocolate Cake",
//     slug: "truffle-chocolate-cake",
//     description: "Award winning chocolate cake.",
//     price: "20.00",
//     category: ["cake", "chocolate"],
//     images: ["../assets/images/cakes/4.avif"],
//     stock: 15,
//     starRating: 4.8,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Doraemon Cake",
//     slug: "doraemon-cake",
//     description: "Cartoon themed birthday cake.",
//     price: "120.00",
//     category: ["cake", "kids"],
//     images: ["../assets/images/cakes/doremon.jpg"],
//     stock: 10,
//     starRating: 5,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Melting Colors Cake",
//     slug: "melting-colors-cake",
//     description: "Colorful artistic cake.",
//     price: "520.00",
//     category: ["cake", "custom"],
//     images: ["../assets/images/cakes/ai-generated-7833232_640.webp"],
//     stock: 8,
//     starRating: 5,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Blueberry Cheesecake",
//     slug: "blueberry-cheesecake",
//     description: "Creamy cheesecake with blueberries.",
//     price: "520.00",
//     category: ["cake", "cheesecake"],
//     images: ["../assets/images/cakes/barry_cake.jpg"],
//     stock: 8,
//     starRating: 4.3,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Minions Themed Cake",
//     slug: "minions-themed-cake",
//     description: "Fun minions birthday cake.",
//     price: "80.00",
//     category: ["cake", "kids"],
//     images: [
//       "../assets/images/cakes/minion-theme-cake_-kids-birthday-cake_-trending-birthday-cakes-for-kids.jpeg",
//     ],
//     stock: 10,
//     starRating: 4.0,
//     creatorSlug: "sweet-cravings",
//   },
//   {
//     name: "Makeup Set Cake",
//     slug: "makeup-set-cake",
//     description: "Stylish cake design for special occasions.",
//     price: "90.00",
//     category: ["cake", "custom"],
//     images: ["../assets/images/cakes/Designer-Cakes-For-Girls.jpeg"],
//     stock: 10,
//     starRating: 4.6,
//     creatorSlug: "sweet-cravings",
//   },
// ];
//  */
